### PR TITLE
Adding endpoints to route calculation

### PR DESCRIPTION
**Pull request by mykobob**
Code to add the calculations for start end endpoints

### CODE REVIEW

**Comment by mykobob** [comment]
PTAL @seanyusa @trevore123

**Comment by seanyusa** [comment]
INTBPFTR @mykobob

**Comment by trevore123** [comment]
^INSWSSBIGMAAT

**Comment by seanyusa** [comment]
Add just one example test. Otherwise LGTM
AJOETOLGTM

**Pull request merged**
